spring:
  application:
    name: mailSync
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  access-token:
    issuer: sipe
    secret-key: dfkdjfkdjkfjskjflnknvkdnvkdnkvndkvsnkdjkfskdf
    expirationMinute: 30

webclient:
  connection:
    timeout:
      millisecond: 100000
    provider:
      name: postmanProvider
      max:
        connections: 1000
      pending:
        acquire:
          max:
            count: -1
          timeout:
            second: 100
  read:
    timeout:
      second: 100
  write:
    timeout:
      second: 100
  provider:
    max:
      in:
        meroty:
          size:
            of:
              byte: 52428800
  block:
    timeout:
      of:
        millis: 100000
