server:
  port: 8000

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true  # 추가

app:
  kakao:
    client-id: 447824b81ba04b0ad083424bf68873dc
    client-secret: ${KAKAO_SECRET}
  topic: ${GMAIL_TOPIC}
  client-id: ${GMAIL_CLIENT}
  client-secret: ${GMAIL_SECRET}

openapi:
  key: ${OPENAPI_KEY}