name: develop deployment
on:
  push:
    branches:
      - "main"
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DEV_DOCKER_ID }}
          password: ${{ secrets.DEV_DOCKER_PW }}
      - name: deploy
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: nowgnas/sipe-thon:test

      # SSH into EC2 and execute the shell script
      - name: Deploy using EC2 script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x ./script/deploy.sh
            sh ./script/deploy.sh
